/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fourthsky_unity_bcast_UnityBroadcastReceiver */

#ifndef _Included_com_fourthsky_unity_androidtools_UnityServiceConnection
#define _Included_com_fourthsky_unity_androidtools_UnityServiceConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fourthsky_unity_androidtools_UnityServiceConnection
 * Method:    nativeOnServiceConnected
 * Signature: (ILandroid/content/ComponentName;Landroid/os/IBinder;)V
 */
JNIEXPORT void JNICALL Java_com_fourthsky_unity_androidtools_UnityServiceConnection_nativeOnServiceConnected
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     com_fourthsky_unity_androidtools_UnityServiceConnection
 * Method:    nativeOnServiceDisconnected
 * Signature: (ILandroid/content/ComponentName;)V
 */
JNIEXPORT void JNICALL Java_com_fourthsky_unity_androidtools_UnityServiceConnection_nativeOnServiceDisconnected
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
