/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fourthsky_unity_androidtools_UnityActivityCallbacks */

#ifndef _Included_com_fourthsky_unity_androidtools_UnityActivityCallbacks
#define _Included_com_fourthsky_unity_androidtools_UnityActivityCallbacks
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fourthsky_unity_androidtools_UnityActivityCallbacks
 * Method:    nativeOnNewIntent
 * Signature: (ILandroid/content/Intent;)V
 */
JNIEXPORT void JNICALL Java_com_fourthsky_unity_androidtools_UnityActivityCallbacks_nativeOnNewIntent
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_fourthsky_unity_androidtools_UnityActivityCallbacks
 * Method:    nativeOnActivityResult
 * Signature: (IIILandroid/content/Intent;)V
 */
JNIEXPORT void JNICALL Java_com_fourthsky_unity_androidtools_UnityActivityCallbacks_nativeOnActivityResult
  (JNIEnv *, jclass, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
