/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fourthsky_unity_bcast_UnityBroadcastReceiver */

#ifndef _Included_com_fourthsky_unity_androidtools_UnityBroadcastReceiver
#define _Included_com_fourthsky_unity_androidtools_UnityBroadcastReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fourthsky_unity_androidtools_UnityBroadcastReceiver
 * Method:    nativeOnReceive
 * Signature: (ILandroid/content/Context;Landroid/content/Intent;)V
 */
JNIEXPORT void JNICALL Java_com_fourthsky_unity_androidtools_UnityBroadcastReceiver_nativeOnReceive
  (JNIEnv *, jobject, jint, jobject, jobject);


#ifdef __cplusplus
}
#endif
#endif
